### ISSUE TITLE
performance evaluation of existing trackers of vot2019 on our own dataset.

### ISSUE THREAD

**Issue by shah0nawaz** [votchallenge/vot-toolkit-python#10]
Hi sir,

I want evaluate the performance of the existing trackers in vot2019 on our own dataset. Please help me how can i do this?. I am using python toolkit for this purpose.

**Comment by lukacu** [comment]
This is not a toolkit issue, please use our support forum. Also, keep in mind that the Python toolkit is currently only officially supported for VOT2020.
