### ISSUE TITLE
setup -- augment name

### ISSUE THREAD

**Issue by zhanglichao** [votchallenge/vot-toolkit-python#14]
Python 3.7.6 is installed in my computer (as required >3.6)
But it seems that there are some augment names are not corresponding for the setup function from distutils.core, as in the setup.py file. E.g. 'long_description_content_type', 'install_requires', 'python_requires', 'entry_points'. While I didn't find in the python [docs  ](https://docs.python.org/3.6/distutils/apiref.html) either.

Maybe something I missed. Hope someone help me find the answer! 

best,
Lichao

**Comment by lukacu** [comment]
As far as I know, some of these flags are pypi extensions, do you get a warning or an error?

**Comment by zhanglichao** [comment]
Hi Luka,

Now I solved it by running the one line command pip … git+.. which works for me.
Tt is very easy for configuration.

Thanks!
Lichao


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Luka Čehovin Zajc<mailto:notifications@github.com>
发送时间: Sunday, May 17, 2020 2:18 PM
收件人: votchallenge/vot-toolkit-python<mailto:vot-toolkit-python@noreply.github.com>
抄送: Lichao<mailto:zhanglichao@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [votchallenge/vot-toolkit-python] setup -- augment name (#14)


As far as I know, some of these flags are pypi extensions, do you get a warning or an error?

**Comment by lukacu** [comment]
Great. Closing the issue.
