### ISSUE TITLE
Couldn't find command 'vot'

### ISSUE THREAD

**Issue by zhanxinrui** [votchallenge/vot-toolkit-python#21]
When I use the command "vot workspace <stack-name> --workspace <workspace-path>"  from the guide in "https://www.votchallenge.net/howto/tutorial_python.html", I got an error info "Command 'vot' not found". 
I guess I need to add some path to my env, but I couldn't find any executable file in "vot" folder.

**Comment by lukacu** [comment]
This usually happens when you do not install the toolkit with pip or run setup.py. You can also run CLI commands using "python -m vot.cli" instead of "vot", but you must have the toolkit in you Python path in either case.

**Comment by zhanxinrui** [comment]
> This usually happens when you do not install the toolkit with pip or run setup.py. You can also run CLI commands using "python -m vot.cli" instead of "vot", but you must have the toolkit in your Python path in either case.

I tried all these ways but have the error still. Finally solved it by changing python from v3.7 to v3.6, I don't know whether it is the python version caused the error or the packages in my envs.  But thanks anyway!
