### ISSUE TITLE
Help in trackers.ini

### ISSUE THREAD

**Issue by gd1925** [votchallenge/vot-toolkit-python#22]
Hi Sir, 
I have been getting this error when I am trying to test the tracker using this command -   vot test D3S

Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vot_wrapper'
Error during tracker execution: Unable to connect to tracker
Terminate

My trackers.ini looks as follows:

[D3S]  # <tracker-name>
label = D3S
protocol = traxpython

command = vot_wrapper

# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /media/imi/HDD Data/Trackers/D3S/pytracking;/media/imi/HDD Data/Trackers/vot-toolkit-python-bk/vot/native/trax/support/python

# Additional environment paths
env_PATH = /home/imi/anaconda3/envs/pytracking/bin/python;${PATH}

Could you please telling me if I am missing something? 
Thank you.

**Comment by xiaozai** [comment]
hi, did you try : 

 paths = /media/imi/HDD Data/Trackers/D3S/pytracking/ ???

**Comment by gd1925** [comment]
Hi @xiaozai ,
Thank you so much for your response. 
I did try it. When I run the command you mentioned, it gives me following error:

Checking for new version
Scanning registry /media/imi/HDD Data/Trackers/vot-workspace/trackers.ini
Found 1 trackers
Generating dummy sequence
Obtaining runtime for tracker D3S
Initializing tracker (1/3)
Running process: /home/imi/anaconda3/envs/pytracking/bin/python -c "import sys;sys.path.insert(0, '/home/imi/D3S/pytracking/'); import vot_wrapper"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/imi/D3S/pytracking/vot_wrapper.py", line 8, in <module>
    from pytracking.tracker.segm import Segm
ModuleNotFoundError: No module named 'pytracking'
Error during tracker execution: Unable to connect to tracker
Terminate

When I give multiple paths like so - 

paths = /home/imi-gauri/D3S/pytracking/ ; /home/imi-gauri/D3S/ 

I get this error - 

Checking for new version
Scanning registry /media/imi/HDD Data/Trackers/vot-workspace/trackers.ini
Found 1 trackers
Generating dummy sequence
Obtaining runtime for tracker D3S
Initializing tracker (1/3)
Running process: /home/imi/anaconda3/envs/pytracking/bin/python -c "import sys;sys.path.insert(0, '/home/imi/D3S/pytracking/ ; /home/imi/D3S/'); import vot_wrapper"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vot_wrapper'
Error during tracker execution: Unable to connect to tracker
Terminate

So, I am not able to give multiple paths.

**Comment by gd1925** [comment]
Hi @xiaozai ,
Thank you so much for your response.
I did try it. When I run the command you mentioned, it gives me following error:

Checking for new version
Scanning registry /media/imi/HDD Data/Trackers/vot-workspace/trackers.ini
Found 1 trackers
Generating dummy sequence
Obtaining runtime for tracker D3S
Initializing tracker (1/3)
Running process: /home/imi/anaconda3/envs/pytracking/bin/python -c "import sys;sys.path.insert(0, '/home/imi/D3S/pytracking/'); import vot_wrapper"
Traceback (most recent call last):
File "", line 1, in
File "/home/imi/D3S/pytracking/vot_wrapper.py", line 8, in
from pytracking.tracker.segm import Segm
ModuleNotFoundError: No module named 'pytracking'
Error during tracker execution: Unable to connect to tracker
Terminate

When I give multiple paths like so -

paths = /home/imi/D3S/pytracking/ ; /home/imi/D3S/

I get this error -

Checking for new version
Scanning registry /media/imi/HDD Data/Trackers/vot-workspace/trackers.ini
Found 1 trackers
Generating dummy sequence
Obtaining runtime for tracker D3S
Initializing tracker (1/3)
Running process: /home/imi/anaconda3/envs/pytracking/bin/python -c "import sys;sys.path.insert(0, '/home/imi/D3S/pytracking/ ; /home/imi/D3S/'); import vot_wrapper"
Traceback (most recent call last):
File "", line 1, in
ModuleNotFoundError: No module named 'vot_wrapper'
Error during tracker execution: Unable to connect to tracker
Terminate

So, I am not able to give multiple paths.

**Comment by xiaozai** [comment]
hi, 

  For the first problem, when pytracking is not found, you may try 
 ```
import sys
sys.path.append(path to pytracking )
```

**Comment by gd1925** [comment]
Hi,
Yes the code is running now.
Thank you so much.
________________________________

**Comment by xiaozai** [comment]
Good, so can the issues be closed?

**Comment by gd1925** [comment]
On running the code, I got the following error. Could you telling me possible reason. 
![Screenshot from 2020-08-26 21-40-03](https://user-images.githubusercontent.com/50822928/91310651-ba288980-e7e4-11ea-924b-8ec29d0885a9.png)

**Comment by lukacu** [comment]
The most likely reason is that the tracker does not support reinitialization. This is the default mode for VOT wrapper, but somehow it was not picked up by the toolkit (it should be). Can you try adding the following line to your ini config: "restart = true". Also, can you paste the first lines of the debug output after you run the CLI, I am interested in TraX handshake.

**Comment by gd1925** [comment]
Hi @lukacu ,

Thank you so much for your reply. It works!
Here is the screenshot -

Thank you once again. 
![Screenshot from 2020-08-27 00-10-35](https://user-images.githubusercontent.com/50822928/91329075-4beec180-e7fa-11ea-86b9-1d709c8d9c4f.png)

**Comment by gd1925** [comment]
Hi @lukacu Sir,

I do not mean to be bothersome but I have been running into another error. The vot test runs successfully. But on running the evaluation command, I encounter following error :

 raise AttributeError("Missing arguments: {}".format(", ".join(unspecified)))
AttributeError: Missing arguments: skip_tags

I found the same error in the Google Support Group on this link - [https://groups.google.com/g/votchallenge-help/c/wUOVxJ16qyE/m/PQax7hC1BwAJ?pli=1](url) . I could not figure out the solution for this error. I am using stack 2018, is that why the problem exists, as it is not vot2020? Could you please suggest to me what I could do to solve it? 

Thank you once again.

**Comment by iraadit** [comment]
Hi @gd1925 , I get the same _skip_tags_ error.
Did you find how to proceed from there?
Thanks

**Comment by gd1925** [comment]
Hi @iraadit, No actually. Not yet. But fortunately, I could make the Matlab toolkit work by downgrading the version from Matlab 2020a to 2017b. So I am now using the VOT Matlab toolkit. But I do wish to make the Python Toolkit work.

**Comment by iraadit** [comment]
I would prefer to get the Python version working too, I have no access to Matlab.
Hope someone will see our problem and have the solution.

**Comment by xiaozai** [comment]
@gd1925 Hi, could you please show the log info or the screenshot of the outputs? I guess it is because of the vot2018 stack file.

**Comment by lukacu** [comment]
The error should be fixed in dev branch for some time, now I have merged it with master. I have used VOT2018 stack in dev branch in the past. Can you test it?

**Comment by gd1925** [comment]
Hi @lukacu and @xiaozai,
Thank you so much for your response. 
The updated code is working perfectly fine now. I was waiting for the evaluations to finish before updating you here but looks like it may take a while on my machine. 
Thank you so much once again.

**Comment by lukacu** [comment]
Great, I am closing the issue now because it is offtopic anyway. Please open a new one if there are more problems.

**Comment by laisimiao** [comment]
> The most likely reason is that the tracker does not support reinitialization. This is the default mode for VOT wrapper, but somehow it was not picked up by the toolkit (it should be). Can you try adding the following line to your ini config: "restart = true". Also, can you paste the first lines of the debug output after you run the CLI, I am interested in TraX handshake.

@lukacu Hi, could I ask a question in your this reply? For my understanding so far, when using vot toolkit, we just provide an interface in which we need call function like `tracker.initialize(img, init_gt)` and `tracker.track(img)`,  so I don't really understand what you said "The most likely reason is that the tracker does not support reinitialization". Because considering above, there are no differences of writing such an interface? 
And I'm appreciate if you could explain where the command "restart=true" it influence or work?
