### ISSUE TITLE
How to decode masks from groundtruth.txt file?

### ISSUE THREAD

**Issue by xiankgx** [votchallenge/vot-toolkit-python#24]
Hi, I've downloaded the dataset using this toolkit CLI using the initialize command.

However, I'm not sure how do I extract the masks from the given groundtruth.txt file. What format are the masks encoded in? Appreciate any help given. Thank you.

**Comment by lukacu** [comment]
The code for mask IO is available in vot/region/io.py although I am not sure why would you want to use it directly, the mask is decoded by the toolkit and made available to the tracker in a matrix form.
