### ISSUE TITLE
NCC running broken down

### ISSUE THREAD

**Issue by JudasDie** [votchallenge/vot-toolkit-python#4]
Hi,
When I run NCC-mask tracker, it raises an error at about the 40th video, 
![image](https://user-images.githubusercontent.com/24988988/77228864-6afc6f80-6b47-11ea-888f-84b74bfd8883.png)

Could you kindly help me to fix it?

**Comment by foolkevin** [comment]
same issue

**Comment by lukacu** [comment]
With the latest updates for #5 we are now unable to reproduce this issue. Can you first try to update and then report if it still occurs?

**Comment by JudasDie** [comment]
The problem has been addressed. Thanks.
