### ISSUE TITLE
Steadily Increasing Memory Consumption

### ISSUE THREAD

**Issue by MasterBin-IIAU** [votchallenge/vot-toolkit-python#5]
when I ran NCCPythonmask tracker, I found that the memory consumption kept increasing quickly and finally caused "**can not allocate memory**" error. (My computer has 64GB memory, which should be enough I guess). 
I also noticed that even though the current sequence had been over, its occupied memory was not set free. So the free memory got less and less. Is this a common phenomenon?

**Comment by alanlukezic** [comment]
Hi, thanks for letting us know about this issue. We are currently working on it and hope that it will be fixed soon.

**Comment by lukacu** [comment]
This problem is fixed now, some native objects were not correctly released. Please update the toolkit as well as its dependency: vot-trax (3.0.1).

**Comment by MasterBin-IIAU** [comment]
Thank you for your efforts!
