### ISSUE TITLE
Found no NVIDIA driver on your system. Please check

### ISSUE THREAD

**Issue by zhanght021** [votchallenge/vot-toolkit-python#6]
`@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=2" "vot=python" "trax.channels=color;" 
@@TRAX:initialize "file:///home/*****/vot-toolkit-python-master/vot2020/sequences/basketball/color/00000001.jpg" "187.0000,211.0000,53.0000,109.0000" 
@@TRAX:state "187.0000,211.0000,53.0000,109.0000" 
@@TRAX:frame "file:///home/*****/vot-toolkit-python-master/vot2020/sequences/basketball/color/00000002.jpg" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/*****/vot-toolkit-python-master/vot2020/tracker/tools/test.py", line 76, in <module>
    tracker = NCCTracker(image, selection)
  File "/home/*****/vot-toolkit-python-master/vot2020/tracker/model.py", line 170, in __init__
    self.location = offset.cuda()
  File "/root/Py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/root/Py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
@@TRAX:quit 
Process did not finish yet`

but i have installed the NVIDIA driver, and without this toolkit ,i can run my code sucessfully ,i don't know where is the problem?

**Comment by lukacu** [comment]
It is most likely that some environmental variable is not set up correctly, I am not sure what else could be the reason. By default, the toolkit copies the environment that it is using, but you may have a custom setup for a tracker.
