### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-python>=4

### ISSUE THREAD

**Issue by fatemehN** [votchallenge/vot-toolkit-python#8]
Hi,
I'm trying to install new VOT-toolkit with the command on my account of Compute Canada:

pip install git+https://github.com/votchallenge/vot-toolkit-python

I got the following error: 

ERROR: Could not find a version that satisfies the requirement opencv-python>=4.0 (from vot-toolkit==0.2.0) (from versions: 3.3.0.10, 3.4.4.19)
ERROR: No matching distribution found for opencv-python>=4.0 (from vot-toolkit==0.2.0)

Before the installation command, I loaded module python/3.6 and activated my virtual environment.

**Comment by lukacu** [comment]
Version 4.0 was used because it is pretty common now. I guess it could work
with lower version but I do not have time to test it myself. Edit
requirements, install and report if it works.

**Comment by fatemehN** [comment]
Thank you for the information. I could successfully install the VOT toolkit without making any changes to the requirements file. I just installed some dependencies and it resolved the problem.
