### ISSUE TITLE
How to load LD_LIBRARY_PATH into the toolkit

### ISSUE THREAD

**Issue by MasterBin-IIAU** [votchallenge/vot-toolkit-python#9]
When integrating my tracker, I encounter the following problems
`ImportError: libnvinfer.so.7: cannot open shared object file: No such file or directory`
But **I can run my tracker correctly without using the toolkit** and I have already covered it in my ~/.bashrc file as below.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/masterbin-iiau/Downloads/Nvidia/TensorRT/TensorRT-7.0.0.11/lib`
So I want to ask "how to load LD_LIBARARY_PATH into the toolkit?"
Thank you

**Comment by lukacu** [comment]
I think that this was answered on our forum already, closing. But just in case, you can use the "linkpaths" property to set a list of paths for libraries.

**Comment by MasterBin-IIAU** [comment]
@lukacu Thank you for your reply.
Could you explain "linkpaths" in more detail? Do you mean env_PATH as shown below?
Thank you

[NCCPython]  # <tracker-name>
label = PyNCC
protocol = traxpython
command = python_ncc
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = <path-to-tracker-source-directory>
# Additional environment paths
env_PATH = <additional-env-paths>;${PATH}
